"""Generated by scripts/gen_buffer_scripts.py from asm/*.s. Do not edit by hand."""

# name -> (ARM machine code, sha256 of the asm source it was assembled from)
PAYLOADS = {
    'trainer-id-probe': (
        bytes.fromhex('ba30d1e1bcc0d1e10c3883e1003080e50100a0e31eff2fe1'),
        '09b4a41aadbc7b8304a41d7b82d04c8ec9c6e600908d0c0b2a85162458f2808c',
    ),
}
