"""Generated by scripts/gen_buffer_scripts.py from asm/*.s. Do not edit by hand."""

# name -> (ARM machine code, sha256 of the asm source it was assembled from)
PAYLOADS = {
    'anchors': (
        bytes.fromhex('08c04fe2103090e500c083e504e083e508d083e50c0083e5101083e5142083e5183083e514c090e51cc083e518c090e520c083e51cc090e524c083e53cc090e528c083e52cc0a0e3b4c3c0e10100a0e31eff2fe1'),
        'b53f6f7ed2bf9f104a26846eeed00570d69e1229d5e21faf74e244aaef733fb6',
    ),
    'memory-dump': (
        bytes.fromhex('10309fe53c3080e50c309fe5b433c0e10100a0e31eff2fe10000000000000000'),
        'fab2c7ad00c6e8099271ac8627b6e3892175429d4aea1be295a678eda303398d',
    ),
    'save-dump': (
        bytes.fromhex('24309fe5000053e30130a0010230a01118c09fe50c3083e03c3080e510309fe5b433c0e10100a0e31eff2fe1000000000000000000000000'),
        '96cbd05d21d8ae1c8ec2093e432d16999f52ed82e4d2f57b7c34f5568ab01ac7',
    ),
    'save-write': (
        bytes.fromhex('44309fe5000053e30130a0010230a01138c09fe50c3083e03c3080e530c09fe5b4c3c0e12c108fe20320a0e100005ce30300000a0100d1e40100c2e401c05ce2fbffff1a0100a0e31eff2fe100000000000000000000000000000000'),
        '428429e918a5e14bbd8961ef34991be4eb9911d5f8d623a25d8bf8bf0279ccdd',
    ),
    'trainer-id-probe': (
        bytes.fromhex('ba30d1e1bcc0d1e10c3883e1003080e50100a0e31eff2fe1'),
        '09b4a41aadbc7b8304a41d7b82d04c8ec9c6e600908d0c0b2a85162458f2808c',
    ),
}
