"""The FRENCH console's own Easy Chat words, read out of its ROM.

Generated by scratchpad/ec_words.py from `--buffer-script string-gather` runs; do
not edit by hand. An Easy Chat id is `(group << 9) | index`, a SLOT, and every
localized ROM fills the slots with its own vocabulary - so `easychat_words.WORDS`,
which comes from the ENGLISH decompilation, names the slot and NOT what a French
console prints in it. This module is what the console itself says.

The four groups that are not here need no reading: EC_GROUP_POKEMON, POKEMON_2,
MOVE_1 and MOVE_2 print from gSpeciesNames / gMoveNames indexed by species number
and move id [decomp:src/easy_chat.c:155], so those slots are language-safe by
construction - `easychat.species_word` and `easychat.move_word` build them.
"""

# group id -> (the run that read it, the sEasyChatGroup_* address, {index: word})
GROUPS = {
    9: (  # EC_GROUP_FEELINGS
        'bs18', 0x083E0D54, {
            0: 'JOYEUX',
            1: 'SATISFAIT',
            2: 'PRESSE',
            3: 'INSATISFAIT',
            4: 'ETOURDI',
            5: 'HEUREUX',
            6: 'BONHEUR',
            7: 'ENERVE',
            8: 'IMPRESSIONNE',
            9: 'DROLE',
            10: 'HUMEUR',
            11: 'DEMORALISE',
            12: 'DECU',
            13: 'RAVI',
            14: 'TRISTE',
            15: 'CONTENT',
            16: 'MECONTENT',
            17: 'DEGOUTE',
            18: 'ECOEURE',
            19: 'RASSURE',
            20: 'EFFRAYE',
            21: 'PASSIONNE',
            22: 'ACHARNE',
            23: 'EN COLERE',
            24: 'COLERE',
            25: 'EFFRAYANT',
            26: 'SOLITUDE',
            27: 'FURIEUX',
            28: 'JOIE',
            29: 'MOTIVE',
            30: 'SOUCIEUX',
            31: 'ZUT',
            32: 'DECOURAGE',
            33: 'MERVEILLEUX',
            34: 'INQUIET',
            35: 'IMPATIENT',
            36: 'ENNUYEUX',
            37: 'CONFIANT',
            38: 'SURPRIS',
            39: 'ETONNE',
            40: 'J’ADORE',
            41: 'DESASTRE',
            42: 'STRESSE',
            43: 'NERVEUX',
            44: 'HUMILIE',
            45: 'FIER',
            46: 'MAUVAIS',
            47: 'DIFFICILE',
            48: 'ATROCE',
            49: 'DEVRAIT',
            50: 'SYMPA',
            51: 'HONTEUX',
            52: 'SURPRISE',
            53: 'PEUR',
            54: 'JE VEUX',
            55: 'ANXIEUX',
            56: 'REJOUI',
            57: 'VOIR',
            58: 'RARE',
            59: 'NEGATIF',
            60: 'FURAX',
            61: 'DANGER',
            62: 'BATTU',
            63: 'EMERVEILLE',
            64: 'SPLENDIDE',
            65: 'ROMANTIQUE',
            66: 'QUESTION',
            67: 'COMPRENDS',
            68: 'COMPREND',
        }),
}

# slot id -> word, flattened: (group << 9) | index, the form an Easy Chat
# operand actually takes.
WORDS = {(group << 9) | index: word
         for group, (_tag, _address, words) in GROUPS.items()
         for index, word in words.items()}
