"""Generated by scripts/gen_field_stubs.py from asm/field/*.s. Do not edit by hand."""

# name -> (THUMB machine code, sha256 of the asm source, {symbol: byte offset})
STUBS = {
    'shiny-seek': (
        bytes.fromhex('f0b50e4c0e4d0f4e104b0f480068418987894f4020680100694389190a0c69438919090c4a407a40082a04d368438019013bf0d1f0bd2060f0bdc046204200036d4ec641736000002c42000300000400'),
        'cc430fb1ce9e148106a2e6b616293f4ed2d21c5240a4c57c1254543d9b77a876',
        {'_start': 0, 'p_add': 68, 'p_cap': 76, 'p_mult': 64, 'p_rng': 60, 'p_sav2ptr': 72},
    ),
}
