"""Generated by scripts/gen_field_stubs.py from asm/field/*.s. Do not edit by hand."""

# name -> (THUMB machine code, sha256 of the asm source, {symbol: byte offset})
STUBS = {
    'mon-seek': (
        bytes.fromhex('f0b5214d214e234b21480068418987894f401c4800680100694389190a0c694389190c0c62407a40082a04d368438019013bf0d1f0bd7a406240240422431924e406a24200d3121b6408192cf9d2124cd440640814d3694389194c00640c69438919090cc9030c430c49e206cd06aa4206d3640949090129f7d1024c2060f0bd014dd3e7204200036d4ec641736000002c42000300000400ffffff0100000040'),
        '2ed14a24de984a4b242f7cabe475d2be59e012a44c5800f6446e73695771fb85',
        {'_start': 0, 'p_add': 140, 'p_cap': 148, 'p_ivmin': 156, 'p_mult': 136, 'p_nature': 152, 'p_rng': 132, 'p_sav2ptr': 144},
    ),
    'shiny-seek': (
        bytes.fromhex('f0b50e4c0e4d0f4e104b0f480068418987894f4020680100694389190a0c69438919090c4a407a40082a04d368438019013bf0d1f0bd2060f0bdc046204200036d4ec641736000002c42000300000400'),
        'cc430fb1ce9e148106a2e6b616293f4ed2d21c5240a4c57c1254543d9b77a876',
        {'_start': 0, 'p_add': 68, 'p_cap': 76, 'p_mult': 64, 'p_rng': 60, 'p_sav2ptr': 72},
    ),
}
