"""Operand widths for the field-script commands, from asm/macros/event.inc.

`ARGS[opcode]` is a tuple of operand sizes in bytes, in order, so an instruction is
1 + sum(ARGS[opcode]) bytes long and `scrcmd.disassemble` can walk a script. Generated by
scripts/gen_scrcmd_args.py; the decomp's macros are the authority for the shapes, and
scrcmd_names.COMMANDS for the names.

`VARIABLE[opcode]` is the other kind: a fixed `head` of operands, one of which (`select`) chooses
the `tail`. Only the trainerbattle family is shaped this way - its ten types carry between one and
four pointers - so an instruction there is 1 + sum(head) + sum(tails[head[select]]) bytes. A type
that is not in `tails` is not a trainerbattle, and the disassembler stops rather than guess.

Do not hand-edit: run the generator. Its docstring has the branch rules and the trap they cost.
"""

# opcode -> (operand widths in bytes)
ARGS = {

    0x00: (),    # nop
    0x01: (),    # nop1
    0x02: (),    # end
    0x03: (),    # return
    0x04: (4,),    # call
    0x05: (4,),    # goto
    0x06: (1, 4),    # goto_if
    0x07: (1, 4),    # call_if
    0x08: (1,),    # gotostd
    0x09: (1,),    # callstd
    0x0A: (1, 1),    # gotostd_if
    0x0B: (1, 1),    # callstd_if
    0x0C: (),    # returnram
    0x0D: (),    # endram
    0x0E: (1,),    # setmysteryeventstatus
    0x0F: (1, 4),    # loadword
    0x10: (1, 1),    # loadbyte
    0x11: (1, 4),    # setptr
    0x12: (1, 4),    # loadbytefromptr
    0x13: (1, 4),    # setptrbyte
    0x14: (1, 1),    # copylocal
    0x15: (4, 4),    # copybyte
    0x16: (2, 2),    # setvar
    0x17: (2, 2),    # addvar
    0x18: (2, 2),    # subvar
    0x19: (2, 2),    # copyvar
    0x1A: (2, 2),    # setorcopyvar
    0x1B: (1, 1),    # compare_local_to_local
    0x1C: (1, 1),    # compare_local_to_value
    0x1D: (1, 4),    # compare_local_to_ptr
    0x1E: (4, 1),    # compare_ptr_to_local
    0x1F: (4, 1),    # compare_ptr_to_value
    0x20: (4, 4),    # compare_ptr_to_ptr
    0x21: (2, 2),    # compare_var_to_value
    0x22: (2, 2),    # compare_var_to_var
    0x23: (4,),    # callnative
    0x24: (4,),    # gotonative
    0x25: (2,),    # special
    0x26: (2, 2),    # specialvar
    0x27: (),    # waitstate
    0x28: (2,),    # delay
    0x29: (2,),    # setflag
    0x2A: (2,),    # clearflag
    0x2B: (2,),    # checkflag
    0x2C: (2, 2),    # initclock
    0x2D: (),    # dotimebasedevents
    0x2E: (),    # gettime
    0x2F: (2,),    # playse
    0x30: (),    # waitse
    0x31: (2,),    # playfanfare
    0x32: (),    # waitfanfare
    0x33: (2, 1),    # playbgm
    0x34: (2,),    # savebgm
    0x35: (),    # fadedefaultbgm
    0x36: (2,),    # fadenewbgm
    0x37: (1,),    # fadeoutbgm
    0x38: (1,),    # fadeinbgm
    0x39: (1, 1, 1, 2, 2),    # warp
    0x3A: (1, 1, 1, 2, 2),    # warpsilent
    0x3B: (1, 1, 1, 2, 2),    # warpdoor
    0x3C: (1, 1),    # warphole
    0x3D: (1, 1, 1, 2, 2),    # warpteleport
    0x3E: (1, 1, 1, 2, 2),    # setwarp
    0x3F: (1, 1, 1, 2, 2),    # setdynamicwarp
    0x40: (1, 1, 1, 2, 2),    # setdivewarp
    0x41: (1, 1, 1, 2, 2),    # setholewarp
    0x42: (2, 2),    # getplayerxy
    0x43: (),    # getpartysize
    0x44: (2, 2),    # additem
    0x45: (2, 2),    # removeitem
    0x46: (2, 2),    # checkitemspace
    0x47: (2, 2),    # checkitem
    0x48: (2,),    # checkitemtype
    0x49: (2, 2),    # addpcitem
    0x4A: (2, 2),    # checkpcitem
    0x4B: (2,),    # adddecoration
    0x4C: (2,),    # removedecoration
    0x4D: (2,),    # checkdecor
    0x4E: (2,),    # checkdecorspace
    0x4F: (2, 4),    # applymovement
    0x50: (2, 4, 1, 1),    # applymovement
    0x51: (2,),    # waitmovement
    0x52: (2, 1, 1),    # waitmovement
    0x53: (2,),    # removeobject
    0x54: (2, 1, 1),    # removeobject
    0x55: (2,),    # addobject
    0x56: (2, 1, 1),    # addobject
    0x57: (2, 2, 2),    # setobjectxy
    0x58: (2, 1, 1),    # showobjectat
    0x59: (2, 1, 1),    # hideobjectat
    0x5A: (),    # faceplayer
    0x5B: (2, 1),    # turnobject
    0x5D: (),    # dotrainerbattle
    0x5E: (),    # gotopostbattlescript
    0x5F: (),    # gotobeatenscript
    0x60: (2,),    # checktrainerflag
    0x61: (2,),    # settrainerflag
    0x62: (2,),    # cleartrainerflag
    0x63: (2, 2, 2),    # setobjectxyperm
    0x64: (2,),    # copyobjectxytoperm
    0x65: (2, 1),    # setobjectmovementtype
    0x66: (),    # waitmessage
    0x67: (4,),    # message
    0x68: (),    # closemessage
    0x69: (),    # lockall
    0x6A: (),    # lock
    0x6B: (),    # releaseall
    0x6C: (),    # release
    0x6D: (),    # waitbuttonpress
    0x6E: (1, 1),    # yesnobox
    0x6F: (1, 1, 1, 1),    # multichoice
    0x70: (1, 1, 1, 1, 1),    # multichoicedefault
    0x71: (1, 1, 1, 1, 1),    # multichoicegrid
    0x72: (),    # drawbox
    0x73: (1, 1, 1, 1),    # erasebox
    0x74: (1, 1, 1, 1),    # drawboxtext
    0x75: (2, 1, 1),    # showmonpic
    0x76: (),    # hidemonpic
    0x77: (1,),    # showcontestpainting
    0x78: (4,),    # braillemessage
    0x79: (2, 1, 2, 4, 4, 1),    # givemon
    0x7A: (2,),    # giveegg
    0x7B: (1, 1, 2),    # setmonmove
    0x7C: (2,),    # checkpartymove
    0x7D: (1, 2),    # bufferspeciesname
    0x7E: (1,),    # bufferleadmonspeciesname
    0x7F: (1, 2),    # bufferpartymonnick
    0x80: (1, 2),    # bufferitemname
    0x81: (1, 2),    # bufferdecorationname
    0x82: (1, 2),    # buffermovename
    0x83: (1, 2),    # buffernumberstring
    0x84: (1, 2),    # bufferstdstring
    0x85: (1, 4),    # bufferstring
    0x86: (4,),    # pokemart
    0x87: (4,),    # pokemartdecoration
    0x88: (4,),    # pokemartdecoration2
    0x89: (2,),    # playslotmachine
    0x8A: (1, 1, 1),    # setberrytree
    0x8B: (),    # choosecontestmon
    0x8C: (),    # startcontest
    0x8D: (),    # showcontestresults
    0x8E: (),    # contestlinktransfer
    0x8F: (2,),    # random
    0x90: (4, 1),    # addmoney
    0x91: (4, 1),    # removemoney
    0x92: (4, 1),    # checkmoney
    0x93: (1, 1, 1),    # showmoneybox
    0x94: (1, 1),    # hidemoneybox
    0x95: (1, 1, 1),    # updatemoneybox
    0x96: (2,),    # getpokenewsactive
    0x97: (1,),    # fadescreen
    0x98: (1, 1),    # fadescreenspeed
    0x99: (2,),    # setflashlevel
    0x9A: (1,),    # animateflash
    0x9B: (4,),    # messageautoscroll
    0x9C: (2,),    # dofieldeffect
    0x9D: (1, 2),    # setfieldeffectargument
    0x9E: (2,),    # waitfieldeffect
    0x9F: (2,),    # setrespawn
    0xA0: (),    # checkplayergender
    0xA1: (2, 2),    # playmoncry
    0xA2: (2, 2, 2, 2),    # setmetatile
    0xA3: (),    # resetweather
    0xA4: (2,),    # setweather
    0xA5: (),    # doweather
    0xA6: (1,),    # setstepcallback
    0xA7: (2,),    # setmaplayoutindex
    0xA8: (2, 1, 1, 1),    # setobjectsubpriority
    0xA9: (2, 1, 1),    # resetobjectsubpriority
    0xAA: (1, 1, 2, 2, 1, 1),    # createvobject
    0xAB: (1, 1),    # turnvobject
    0xAC: (2, 2),    # opendoor
    0xAD: (2, 2),    # closedoor
    0xAE: (),    # waitdooranim
    0xAF: (2, 2),    # setdooropen
    0xB0: (2, 2),    # setdoorclosed
    0xB1: (1, 2, 2, 2),    # addelevmenuitem
    0xB2: (),    # showelevmenu
    0xB3: (2,),    # checkcoins
    0xB4: (2,),    # addcoins
    0xB5: (2,),    # removecoins
    0xB6: (2, 1, 2),    # setwildbattle
    0xB7: (),    # dowildbattle
    0xB8: (4,),    # setvaddress
    0xB9: (4,),    # vgoto
    0xBA: (4,),    # vcall
    0xBB: (1, 4),    # vgoto_if
    0xBC: (1, 4),    # vcall_if
    0xBD: (4,),    # vmessage
    0xBE: (4,),    # vbuffermessage
    0xBF: (1, 4),    # vbufferstring
    0xC0: (1, 1),    # showcoinsbox
    0xC1: (1, 1),    # hidecoinsbox
    0xC2: (1, 1),    # updatecoinsbox
    0xC3: (1,),    # incrementgamestat
    0xC4: (1, 1, 1, 2, 2),    # setescapewarp
    0xC5: (),    # waitmoncry
    0xC6: (1, 2),    # bufferboxname
    0xC7: (1,),    # textcolor
    0xC8: (4,),    # loadhelp
    0xC9: (),    # unloadhelp
    0xCA: (),    # signmsg
    0xCB: (),    # normalmsg
    0xCC: (1, 4),    # comparestat
    0xCD: (2,),    # setmonmodernfatefulencounter
    0xCE: (2,),    # checkmonmodernfatefulencounter
    0xCF: (),    # trywondercardscript
    0xD0: (2,),    # setworldmapflag
    0xD1: (1, 1, 1, 2, 2),    # warpspinenter
    0xD2: (2, 1),    # setmonmetlocation
    0xD3: (4,),    # getbraillestringwidth
    0xD4: (1, 2, 2),    # bufferitemnameplural
}

# opcode -> (head widths, index of the head operand that picks the tail,
#           {that operand's value: tail widths})
VARIABLE = {
    0x5C: {    # trainerbattle
        "head": (1, 2, 2),
        "select": 0,
        "tails": {
            0: (4, 4),
            1: (4, 4, 4),
            2: (4, 4, 4),
            3: (4,),
            4: (4, 4, 4),
            5: (4, 4),
            6: (4, 4, 4, 4),
            7: (4, 4, 4),
            8: (4, 4, 4, 4),
            9: (4, 4),
        },
    },
}

