"""The 444 entries of `gSpecials`, in table order [decomp:data/specials.inc].

The index IS the special: `ScrCmd_special` reads a u16, bounds-checks `&gSpecials[i]` against
`gSpecialsEnd` and calls through it [decomp:src/scrcmd.c:101]. Generated by
scripts/gen_special_names.py; the names are the decomp's own.

The table's address needed no search: bs92 dumped ScrCmd_special and read 0x081639FC and 0x081640EC
out of its literal pool, and 0x081640EC - 0x081639FC is 0x6F0 = 444 * 4, which is the length of
this list. It also lands immediately after gSpecialVars (0x081639A8 + 21 * 4), which is the order
ld_script puts them in. docs/buffer_script.md.

MANY ENTRIES SHARE A FUNCTION. `NullFieldSpecial` appears dozens of times, so a dump of the table
proves its own alignment: those indices must all come back with ONE address.
"""

SPECIALS = (

    'HealPlayerParty', 'SetCableClubWarp', 'DoCableClubWarp',
    'ReturnFromLinkRoom', 'CleanupLinkRoomState', 'ExitLinkRoom',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'TryBattleLinkup', 'TryTradeLinkup',
    'TryRecordMixLinkup', 'CloseLink', 'EnterColosseumPlayerSpot',
    'EnterTradeSeat', 'StartWiredCableClubTrade', 'CableClub_AskSaveTheGame',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'SavePlayerParty', 'LoadPlayerParty', 'ChooseHalfPartyForBattle',
    'Script_ShowLinkTrainerCard', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'IsEnigmaBerryValid',
    'GetTrainerBattleMode', 'ShowTrainerIntroSpeech', 'ShowTrainerCantBattleSpeech',
    'Script_HasTrainerBeenFought', 'EndTrainerApproach', 'PlayTrainerEncounterMusic',
    'ShouldTryRematchBattle', 'IsTrainerReadyForRematch', 'StartRematchBattle',
    'ShowPokemonStorageSystemPC', 'HasEnoughMonsForDoubleBattle', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'HasLeadMonBeenRenamed', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'TryContestLinkup',
    'Field_AskSaveTheGame', 'DoWateringBerryTreeAnim', 'ShowEasyChatScreen',
    'ShowEasyChatMessage', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'GetHeracrossSizeRecordInfo',
    'CompareHeracrossSize', 'GetMagikarpSizeRecordInfo', 'CompareMagikarpSize',
    'NameRaterWasNicknameChanged', 'BufferMonNickname', 'IsMonOTIDNotPlayers',
    'NullFieldSpecial', 'NullFieldSpecial', 'BufferRandomHobbyOrLifestyleString',
    'NullFieldSpecial', 'RegisteredItemHandleBikeSwap', 'CalculatePlayerPartyCount',
    'CountPartyNonEggMons', 'CountPartyAliveNonEggMons_IgnoreVar0x8004Slot', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'ShowFieldMessageStringVar4', 'DrawWholeMapView', 'GetPlayerXY',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'GetPlayerTrainerIdOnesDigit', 'BufferBigGuyOrBigGirlString', 'BufferSonOrDaughterString',
    'SetHiddenItemFlag', 'NullFieldSpecial', 'NullFieldSpecial',
    'Overworld_PlaySpecialMapMusic', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'StartOldManTutorialBattle', 'ChangePokemonNickname',
    'ChoosePartyMon', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'Script_IsFanClubMemberFanOfPlayer', 'Script_GetNumFansOfPlayerInTrainerFanClub',
    'Script_BufferFanClubTrainerName', 'Script_TryLoseFansFromPlayTimeAfterLinkBattle', 'Script_TryLoseFansFromPlayTime',
    'Script_SetPlayerGotFirstFans', 'Script_UpdateTrainerFanClubGameClear', 'Script_TryGainNewFanFromCounter',
    'RockSmashWildEncounter', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'GetBattleOutcome', 'GetDaycareMonNicknames', 'GetDaycareState',
    'RejectEggFromDayCare', 'GiveEggFromDaycare', 'SetDaycareCompatibilityString',
    'GetSelectedMonNicknameAndSpecies', 'StoreSelectedPokemonInDaycare', 'ChooseSendDaycareMon',
    'ShowDaycareLevelMenu', 'GetNumLevelsGainedFromDaycare', 'GetDaycareCost',
    'TakePokemonFromDaycare', 'ScriptHatchMon', 'EggHatch',
    'DaycareMonReceivedMail', 'ShowBattleRecords', 'IsEnoughForCostInVar0x8005',
    'SubtractMoneyFromVar0x8005', 'TryFieldPoisonWhiteOut', 'SetCB2WhiteOut',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'EnterSafariMode', 'ExitSafariMode',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'GetPokedexCount',
    'GetProfOaksRatingMessage', 'AnimatePcTurnOn', 'AnimatePcTurnOff',
    'GetElevatorFloor', 'NullFieldSpecial', 'NullFieldSpecial',
    'ChooseMonForMoveRelearner', 'SelectMoveDeleterMove', 'MoveDeleterForgetMove',
    'BufferMoveDeleterNicknameAndMove', 'GetNumMovesSelectedMonHas', 'TeachMoveRelearnerMove',
    'NullFieldSpecial', 'NullFieldSpecial', 'GetPlayerAvatarBike',
    'NullFieldSpecial', 'NullFieldSpecial', 'GetLeadMonFriendship',
    'BattleTowerMapScript2', 'ChooseNextBattleTowerTrainer', 'CheckPartyBattleTowerBanlist',
    'PrintBattleTowerTrainerGreeting', 'BufferEReaderTrainerGreeting', 'StartSpecialBattle',
    'SetBattleTowerProperty', 'BattleTowerUtil', 'SetBattleTowerParty',
    'SaveBattleTowerProgress', 'BattleTower_SoftReset', 'DetermineBattleTowerPrize',
    'GiveBattleTowerPrize', 'AwardBattleTowerRibbons', 'ChooseBattleTowerPlayerParty',
    'ValidateEReaderTrainer', 'NullFieldSpecial', 'ReducePlayerPartyToThree',
    'BedroomPC', 'PlayerPC', 'ShowTownMap',
    'GetInGameTradeSpeciesInfo', 'CreateInGameTradePokemon', 'DoInGameTradeScene',
    'GetTradeSpecies', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'CreatePCMenu', 'HallOfFamePCBeginFade',
    'ShowDiploma', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'LookThroughPorthole', 'DoSoftReset', 'EnterHallOfFame',
    'AnimateElevator', 'NullFieldSpecial', 'SpawnCameraObject',
    'RemoveCameraObject', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'BufferEReaderTrainerName', 'GetRandomSlotMachineId', 'GetPlayerFacingDirection',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'NullFieldSpecial', 'LeadMonHasEffortRibbon', 'GiveLeadMonEffortRibbon',
    'AreLeadMonEVsMaxedOut', 'Script_FacePlayer', 'Script_ClearHeldMovement',
    'InitRoamer', 'NullFieldSpecial', 'PlayerHasGrassPokemonInParty',
    'NullFieldSpecial', 'NullFieldSpecial', 'IsStarterFirstStageInParty',
    'NullFieldSpecial', 'IsThereRoomInAnyBoxForMorePokemon', 'NullFieldSpecial',
    'DrawElevatorCurrentFloorWindow', 'NullFieldSpecial', 'IsPokerusInParty',
    'SetIcefallCaveCrackedIceMetatiles', 'ShakeScreen', 'StartGroudonKyogreBattle',
    'StartLegendaryBattle', 'StartRegiBattle', 'SetUpTrainerMovement',
    'NullFieldSpecial', 'NullFieldSpecial', 'StartDroughtWeatherBlend',
    'DoDiveWarp', 'DoFallWarp', 'NullFieldSpecial',
    'NullFieldSpecial', 'SetEReaderTrainerGfxId', 'StartSouthernIslandBattle',
    'NullFieldSpecial', 'NullFieldSpecial', 'NullFieldSpecial',
    'GetPartyMonSpecies', 'IsSelectedMonEgg', 'NullFieldSpecial',
    'NullFieldSpecial', 'LoadPlayerBag', 'Script_FadeOutMapMusic',
    'NullFieldSpecial', 'NullFieldSpecial', 'HasAllKantoMons',
    'IsMonOTNameNotPlayers', 'NullFieldSpecial', 'Dummy_TryEnableBravoTrainerBattleTower',
    'DoesPartyHaveEnigmaBerry', 'NullFieldSpecial', 'SetPostgameFlags',
    'StartMarowakBattle', 'ForcePlayerOntoBike', 'ListMenu',
    'ReturnToListMenu', 'DoPicboxCancel', 'SetVermilionTrashCans',
    'SeafoamIslandsB4F_CurrentDumpsPlayerOnLand', 'SampleResortGorgeousMonAndReward', 'CheckAddCoins',
    'GetDaycarePokemonCount', 'CloseElevatorCurrentFloorWindow', 'ForcePlayerToStartSurfing',
    'GetStarterSpecies', 'SetSeenMon', 'VsSeekerResetObjectMovementAfterChargeComplete',
    'ShouldShowBoxWasFullMessage', 'ChangeBoxPokemonNickname', 'UpdateTrainerCardPhotoIcons',
    'StickerManGetBragFlags', 'SetUsedPkmnCenterQuestLogEvent', 'IsWirelessAdapterConnected',
    'TryBecomeLinkLeader', 'TryJoinLinkGroup', 'RunUnionRoom',
    'ShowWirelessCommunicationScreen', 'EnableNationalPokedex', 'SetWalkingIntoSignVars',
    'DisableMsgBoxWalkaway', 'VsSeekerFreezeObjectsAfterChargeComplete', 'SetFlavorTextFlagFromSpecialVars',
    'UpdatePickStateFromSpecialVar8005', 'OverworldWhiteOutGetMoneyLoss', 'PutMonInRoute5Daycare',
    'GetCostToWithdrawRoute5DaycareMon', 'IsThereMonInRoute5Daycare', 'GetNumLevelsGainedForRoute5DaycareMon',
    'TakePokemonFromRoute5Daycare', 'DoSeagallopFerryScene', 'DoesPlayerPartyContainSpecies',
    'Script_SetHelpContext', 'BackupHelpContext', 'RestoreHelpContext',
    'ValidateSavedWonderCard', 'SetUnlockedPokedexFlags', 'InitUnionRoom',
    'BufferUnionRoomPlayerName', 'QuestLog_StartRecordingInputsAfterDeferredEvent', 'GetMartClerkObjectId',
    'GetMysteryGiftCardStat', 'GetQuestLogState', 'QuestLog_CutRecording',
    'WonderNews_GetRewardInfo', 'GetPCBoxToSendMon', 'OpenMuseumFossilPic',
    'CloseMuseumFossilPic', 'ChooseMonForMoveTutor', 'ChooseMonForWirelessMinigame',
    'SetBattledTrainerFlag', 'SetHelpContextForMap', 'DoSSAnneDepartureCutscene',
    'IsPokemonJumpSpeciesInParty', 'IsNationalPokedexEnabled', 'CallTrainerTowerFunc',
    'ShowPokemonJumpRecords', 'BufferTMHMMoveName', 'DaisyMassageServices',
    'HelpSystem_Disable', 'HelpSystem_Enable', 'SetPostgameFlags',
    'HasAtLeastOneBerry', 'DisplayBerryPowderVendorMenu', 'RemoveBerryPowderVendorMenu',
    'Script_HasEnoughBerryPowder', 'Script_TakeBerryPowder', 'PrintPlayerBerryPowderAmount',
    'DoPokemonLeagueLightingEffect', 'ShowBerryCrushRankings', 'CapeBrinkGetMoveToTeachLeadPokemon',
    'HasLearnedAllMovesFromCapeBrinkTutor', 'DoCredits', 'ShowDodrioBerryPickingRecords',
    'DrawSeagallopDestinationMenu', 'GetSelectedSeagallopDestination', 'GetSeagallopNumber',
    'GetPlayerFacingDirection', 'DoDeoxysTriangleInteraction', 'SetDeoxysTrianglePalette',
    'IsPlayerLeftOfVermilionSailor', 'IsBadEggInParty', 'ReadTrainerTowerAndValidate',
    'HasAllMons', 'IsPlayerNotInTrainerTowerLobby', 'BrailleCursorToggle',
    'Script_ResetUnionRoomTrade', 'PlayerPartyContainsSpeciesWithPlayerID', 'AnimateTeleporterHousing',
    'IsDodrioInParty', 'AnimateTeleporterCable', 'InitElevatorFloorSelectMenuPos',
    'UpdateLoreleiDollCollection', 'LoopWingFlapSound', 'CreateEnemyEventMon',
)

SPECIAL_COUNT = len(SPECIALS)
SPECIALS_TABLE_SIZE = SPECIAL_COUNT * 4


def read_table(dump, base, first=0):
    """-> [(index, name, address, thumb_bit)] for a dump of gSpecials at `base` starting at
    entry `first`. A dump is at most 256 entries, so `first` is how the rest is read."""
    out = []
    for i in range(min(SPECIAL_COUNT - first, len(dump) // 4)):
        value = int.from_bytes(bytes(dump[4 * i:4 * i + 4]), "little")
        out.append((first + i, SPECIALS[first + i], value & ~1, bool(value & 1)))
    return out


def index(name):
    """-> the index of a special by the decomp's name. Raises if the name is used more than once,
    because then the caller has to say WHICH one."""
    hits = [i for i, known in enumerate(SPECIALS) if known == name]
    if not hits:
        raise KeyError(f"{name!r} is not in gSpecials")
    if len(hits) > 1:
        raise KeyError(f"{name!r} appears at {len(hits)} indices: {hits}")
    return hits[0]
