"""Every message BDSP's own protocol carries, by data id [opendpr:Dpr/NetworkUtils].

Generated by scripts/gen_bdsp_netdata.py from a TeamLumi/opendpr checkout. `NetDataParser` registers
one `ANetData<T>` per message, each declaring its own `DataID` byte and one plain struct `T`, so
none of this was read off a capture and none of it is a guess. `pokeldn.bdsp.room` is what encodes
and decodes; this is only the table.

THE IDS ARE NIBBLE-GROUPED - 0x01..0x09, 0x10..0x19, 0x20..0x29, and so on, no low nibble ever
reaching 0xA - so a gap in the numbering is the grouping and not a message this table is missing.

FIELDS is the packed layout, and PACKED is measured, not assumed: a real console's NetJoinData is
17 bytes with `short InitRotY` at offset 3, where C#'s default alignment would put it at 4 and make
the message 20. A payload whose struct holds a string, an array or a list has NO entry here - its
layout is not decidable from the source, and inventing one is what this file exists to prevent.

Each FIELDS entry is (name, C# type, struct format); a nested struct is inlined under a dotted name,
because the wire carries fields and not structs.
"""


NAMES = {
    0x01: ('NetJoinData', 'JoinData'),
    0x02: ('NetPosData', 'PosListData'),
    0x03: ('NetEmotionData', 'EmotionData'),
    0x04: ('NetCharacterStateData', 'StateData'),
    0x05: ('NetDataTranerCardData', 'TranerData'),
    0x06: ('NetDataTalkData', 'TalkData'),
    0x07: ('NetDataTransitionData', 'TransitionData'),
    0x08: ('NetDataSelectData', 'SelectData'),
    0x09: ('NetDataBattleTypeData', 'BattleTypeData'),
    0x10: ('NetDataTalkCancelEndData', 'CancelEndData'),
    0x11: ('NetDataBattleRuleCancelData', 'BattleCancelData'),
    0x12: ('NetRequestData', 'RequestData'),
    0x13: ('NetTradePokeData', 'TradePokeData'),
    0x14: ('NetDataRecodeData', 'NetRecodeData'),
    0x15: ('NetDataAttachSealNetData', 'BallDecoData'),
    0x16: ('NetUgJoinData', 'UgJoinData'),
    0x17: ('NetZoneData', 'PosZoneData'),
    0x18: ('NetSecretBaseData', 'UgSecretBase'),
    0x19: ('NetDigData', 'DigPosData'),
    0x20: ('NetDataTransitionAfterData', 'TransitionAfterData'),
    0x21: ('NetDataTradeReadyOkData', 'ReadyOkData'),
    0x22: ('NetDataStandbyWaitListData', 'StanbyListData'),
    0x23: ('NetDataIsMatchWaitData', 'MatchWaitData'),
    0x24: ('NetDataTradeTranerData', 'TradeTranerData'),
    0x25: ('NetDataCurrentFlowCancelData', 'CancelData'),
    0x26: ('NetDigJoinData', 'DigJoinData'),
    0x27: ('NetDigAttackData', 'DigAttackData'),
    0x28: ('NetDigEndData', 'DigEndData'),
    0x29: ('NetDigGroupIdData', 'UgStationID_to_DigFossilIDList'),
    0x30: ('NetDataBattleMatchingJoin', 'JoinPlayerData'),
    0x31: ('NetDataBattleMatchingLeave', 'BattleMatchingBaseData'),
    0x32: ('NetDataBattleMatchingReady', 'BattleMatchingBaseData'),
    0x33: ('NetDataBattleMatchingState', 'StationIndexData'),
    0x34: ('NetDataBattleMatchingSelectTeam', 'StationIndexData'),
    0x35: ('NetDataBattleMatchingSelectRuleMember', 'BattleMatchingBaseData'),
    0x36: ('NetDataBattleMatchingDecideRuleMember', 'BattleMatchingBaseData'),
    0x37: ('NetDataBattleMatchingRule', 'BattleMatchingRuleData'),
    0x38: ('NetDataBattleMatchingSelectPokemon', 'BattleMatchingPokeData'),
    0x39: ('NetDataBattleMatchingCancelPokemon', 'BattleMatchingBaseData'),
    0x40: ('NetDataBattleMatchingResume', 'StationIndexData'),
    0x41: ('NetSecretBaseInfo', 'PosZoneData'),
    0x42: ('NetPlayerNameData', 'NetPlayerName'),
    0x43: ('NetPosZoneData', 'PosZoneData'),
    0x44: ('NetJoinDigPermission', 'JoinDigPermission'),
    0x45: ('NetDataReturnSelectData', 'ReturnSelectData'),
    0x46: ('NetDataTradePokeCheckOkData', 'TradePokeCheckOkData'),
    0x47: ('NetKousekiAdd', 'IntData'),
    0x48: ('NetBonusStart', 'Dummy'),
    0x49: ('NetRemainBonusTime', 'IntData'),
    0x50: ('NetKousekiCount', 'IntData'),
    0x51: ('NetDigJoinMemberCount', 'IntData'),
    0x52: ('NetDataBattleMatchingCountDown', 'BattleMatchingCountDownData'),
    0x54: ('NetSecretBaseUpdate', 'UgSecretBase'),
    0x55: ('NetNaminoriData', 'BoolData'),
    0x56: ('NetDataColiseumJoinDataData', 'ColiseumJoinData'),
    0x57: ('NetDataColiseumLeaveData', 'ColiseumLeaveData'),
    0x58: ('NetDataColiseumReadyPointJoinData', 'ColiseumReadyPointJoinData'),
    0x59: ('NetDataStandbyWaitData', 'StandbyData'),
    0x60: ('NetDataRecodeTradeData', 'RecodeTradeData'),
    0x61: ('NetDigTableData', 'UgStationID_to_DigFossilIDList'),
    0x62: ('NetDataBattleMatchingDecideTeam', 'BattleMatchingBaseData'),
    0x63: ('NetDataTalkReserveData', 'TalkReserveData'),
    0x64: ('NetDataTalkReserveResultData', 'TalkReserveResultData'),
    0x65: ('NetDataColiseumConfirmEntryData', 'ColiseumConfirmEntryData'),
    0x66: ('NetDataColiseumReplyEntryData', 'ColiseumReplyEntryData'),
}


# The packed layout of every payload whose struct is entirely blittable.
FIELDS = {
    0x01: (   # NetJoinData
        ('avatarId', 'byte', 'B'),
        ('colorId', 'byte', 'B'),
        ('cassetVersion', 'byte', 'B'),
        ('InitRotY', 'short', 'h'),
        ('InitPos', 'Vector3', '3f'),
    ),
    0x03: (   # NetEmotionData
        ('emoId', 'byte', 'B'),
    ),
    0x04: (   # NetCharacterStateData
        ('state', 'byte', 'B'),
        ('isRecruiment', 'byte', 'B'),
    ),
    0x05: (   # NetDataTranerCardData
        ('fashionId', 'byte', 'B'),
        ('bodyType', 'byte', 'B'),
        ('genderid', 'byte', 'B'),
        ('langId', 'byte', 'B'),
        ('tranerRank', 'byte', 'B'),
        ('cardData.startTime', 'long', 'q'),
        ('cardData.tranerId', 'uint', 'I'),
        ('cardData.money', 'uint', 'I'),
        ('cardData.zukanCount', 'uint', 'I'),
        ('cardData.styleRank', 'uint', 'I'),
        ('cardData.beatifulRank', 'uint', 'I'),
        ('cardData.cuteRank', 'uint', 'I'),
        ('cardData.cleverRank', 'uint', 'I'),
        ('cardData.strongRank', 'uint', 'I'),
        ('cardData.renshouSingle', 'uint', 'I'),
        ('cardData.renshouDouble', 'uint', 'I'),
        ('cardData.renshouSingleMaster', 'uint', 'I'),
        ('cardData.renshouDoubleMaster', 'uint', 'I'),
        ('cardData.clearTime', 'uint', 'I'),
        ('cardData.digFossilPlayCount', 'short', 'h'),
        ('cardData.playTimeHour', 'ushort', 'H'),
        ('cardData.playTimeMinute', 'ushort', 'H'),
        ('cardData.tagIndex', 'byte', 'B'),
        ('cardData.isZukanGet', 'byte', 'B'),
        ('cardData.cookingCount', 'byte', 'B'),
        ('cardData.getHaveStatueKindNum', 'byte', 'B'),
    ),
    0x06: (   # NetDataTalkData
        ('talkOpcSexId', 'byte', 'B'),
        ('talkState', 'TalkState', 'i'),
    ),
    0x07: (   # NetDataTransitionData
        ('transitionType', 'byte', 'B'),
        ('isRecruitment', 'byte', 'B'),
    ),
    0x08: (   # NetDataSelectData
        ('index', 'byte', 'B'),
    ),
    0x09: (   # NetDataBattleTypeData
        ('type', 'byte', 'B'),
    ),
    0x10: (   # NetDataTalkCancelEndData
        ('IsRecruitment', 'byte', 'B'),
        ('emoticonStateType', 'byte', 'B'),
    ),
    0x11: (   # NetDataBattleRuleCancelData
        ('IsCancel', 'byte', 'B'),
    ),
    0x12: (   # NetRequestData
        ('RequestDataID', 'byte', 'B'),
    ),
    0x16: (   # NetUgJoinData
        ('avatarId', 'byte', 'B'),
        ('colorId', 'byte', 'B'),
        ('zoneID', 'short', 'h'),
        ('InitRotY', 'short', 'h'),
        ('InitPos', 'Vector3', '3f'),
    ),
    0x17: (   # NetZoneData
        ('pos', 'Vector3', '3f'),
        ('zoneID', 'ZoneID', 'i'),
    ),
    0x19: (   # NetDigData
        ('zoneID', 'ZoneID', 'i'),
        ('MainPos', 'Vector2Int', '2i'),
        ('digPos1.GridX', 'short', 'h'),
        ('digPos1.GridY', 'short', 'h'),
        ('digPos2.GridX', 'short', 'h'),
        ('digPos2.GridY', 'short', 'h'),
    ),
    0x20: (   # NetDataTransitionAfterData
        ('isTransitionAfetr', 'byte', 'B'),
    ),
    0x21: (   # NetDataTradeReadyOkData
        ('isTradeOk', 'byte', 'B'),
        ('tradeState', 'byte', 'B'),
    ),
    0x23: (   # NetDataIsMatchWaitData
        ('isMatchWait', 'byte', 'B'),
    ),
    0x25: (   # NetDataCurrentFlowCancelData
        ('isError', 'byte', 'B'),
    ),
    0x26: (   # NetDigJoinData
        ('TonariHoriPosition', 'Vector2Int', '2i'),
    ),
    0x27: (   # NetDigAttackData
        ('position', 'Vector2', '2f'),
        ('isHammer', 'bool', '?'),
    ),
    0x28: (   # NetDigEndData
        ('endReason', 'byte', 'B'),
    ),
    0x30: (   # NetDataBattleMatchingJoin
        ('id', 'uint', 'I'),
        ('stationIndex', 'byte', 'B'),
        ('index', 'byte', 'B'),
        ('language', 'byte', 'B'),
        ('colorId', 'byte', 'B'),
        ('avatarId', 'byte', 'B'),
        ('sexId', 'byte', 'B'),
        ('cassetVersion', 'byte', 'B'),
    ),
    0x31: (   # NetDataBattleMatchingLeave
    ),
    0x32: (   # NetDataBattleMatchingReady
    ),
    0x33: (   # NetDataBattleMatchingState
        ('stationIndex', 'byte', 'B'),
        ('index', 'byte', 'B'),
    ),
    0x34: (   # NetDataBattleMatchingSelectTeam
        ('stationIndex', 'byte', 'B'),
        ('index', 'byte', 'B'),
    ),
    0x35: (   # NetDataBattleMatchingSelectRuleMember
    ),
    0x36: (   # NetDataBattleMatchingDecideRuleMember
    ),
    0x37: (   # NetDataBattleMatchingRule
        ('pokemonNum', 'byte', 'B'),
        ('pokemonLevel', 'byte', 'B'),
        ('isBanLegendPokemon', 'byte', 'B'),
        ('isBanSamePokemon', 'byte', 'B'),
        ('isBanSameItem', 'byte', 'B'),
    ),
    0x39: (   # NetDataBattleMatchingCancelPokemon
    ),
    0x40: (   # NetDataBattleMatchingResume
        ('stationIndex', 'byte', 'B'),
        ('index', 'byte', 'B'),
    ),
    0x41: (   # NetSecretBaseInfo
        ('pos', 'Vector3', '3f'),
        ('zoneID', 'ZoneID', 'i'),
    ),
    0x43: (   # NetPosZoneData
        ('pos', 'Vector3', '3f'),
        ('zoneID', 'ZoneID', 'i'),
    ),
    0x44: (   # NetJoinDigPermission
        ('isOK', 'bool', '?'),
    ),
    0x45: (   # NetDataReturnSelectData
        ('isReturnSelect', 'byte', 'B'),
    ),
    0x46: (   # NetDataTradePokeCheckOkData
        ('isCheckOk', 'byte', 'B'),
    ),
    0x47: (   # NetKousekiAdd
        ('Value', 'int', 'i'),
    ),
    0x48: (   # NetBonusStart
    ),
    0x49: (   # NetRemainBonusTime
        ('Value', 'int', 'i'),
    ),
    0x50: (   # NetKousekiCount
        ('Value', 'int', 'i'),
    ),
    0x51: (   # NetDigJoinMemberCount
        ('Value', 'int', 'i'),
    ),
    0x52: (   # NetDataBattleMatchingCountDown
        ('timeCount', 'ushort', 'H'),
    ),
    0x55: (   # NetNaminoriData
        ('Value', 'bool', '?'),
    ),
    0x56: (   # NetDataColiseumJoinDataData
        ('JoinPointIndex', 'byte', 'B'),
    ),
    0x57: (   # NetDataColiseumLeaveData
        ('LeavePointIndex', 'byte', 'B'),
    ),
    0x58: (   # NetDataColiseumReadyPointJoinData
        ('PointIndex', 'byte', 'B'),
        ('isJoin', 'byte', 'B'),
    ),
    0x59: (   # NetDataStandbyWaitData
        ('isAddPlayer', 'byte', 'B'),
        ('hostIndex', 'byte', 'B'),
        ('myIndex', 'byte', 'B'),
        ('langId', 'byte', 'B'),
    ),
    0x60: (   # NetDataRecodeTradeData
        ('isRecodeTrade', 'byte', 'B'),
    ),
    0x62: (   # NetDataBattleMatchingDecideTeam
    ),
    0x63: (   # NetDataTalkReserveData
    ),
    0x64: (   # NetDataTalkReserveResultData
        ('IsCanTalk', 'byte', 'B'),
        ('IsRecruitment', 'byte', 'B'),
        ('emoticonStateType', 'byte', 'B'),
    ),
    0x65: (   # NetDataColiseumConfirmEntryData
        ('number', 'byte', 'B'),
    ),
    0x66: (   # NetDataColiseumReplyEntryData
        ('answer', 'byte', 'B'),
    ),
}


# The payloads whose struct is not blittable - a string, an array or a list. The id and
# the name are known; the layout is not, and must be measured before it is written down.
OPAQUE = {
    0x02: 'PosListData',   # NetPosData
    0x13: 'TradePokeData',   # NetTradePokeData
    0x14: 'NetRecodeData',   # NetDataRecodeData
    0x15: 'BallDecoData',   # NetDataAttachSealNetData
    0x18: 'UgSecretBase',   # NetSecretBaseData
    0x22: 'StanbyListData',   # NetDataStandbyWaitListData
    0x24: 'TradeTranerData',   # NetDataTradeTranerData
    0x29: 'UgStationID_to_DigFossilIDList',   # NetDigGroupIdData
    0x38: 'BattleMatchingPokeData',   # NetDataBattleMatchingSelectPokemon
    0x42: 'NetPlayerName',   # NetPlayerNameData
    0x54: 'UgSecretBase',   # NetSecretBaseUpdate
    0x61: 'UgStationID_to_DigFossilIDList',   # NetDigTableData
}
