#!/usr/bin/env python3
"""Regenerate frlgsim/scrcmd_args.py from the decompilation's own script macros.

A field script is a byte stream: one opcode then its operands, and the operand WIDTHS are what say
where the next opcode starts. asm/macros/event.inc is the authority - each macro emits its opcode
as `.byte` and then a `.byte`/`.2byte`/`.4byte` per argument - so the whole table can be read out of
it rather than transcribed. scrcmd_names.COMMANDS already gives the names; this gives the shapes,
and together they disassemble any script the console holds.

    ./.venv/bin/python scripts/gen_scrcmd_args.py [~/pokefirered]
"""
import pathlib
import re
import sys

DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "~/pokefirered").expanduser()
OUT = pathlib.Path(__file__).resolve().parent.parent / "frlgsim" / "scrcmd_args.py"

HEADER = '''"""Operand widths for the field-script commands, from asm/macros/event.inc.

`ARGS[opcode]` is a tuple of operand sizes in bytes, in order, so an instruction is
1 + sum(ARGS[opcode]) bytes long and `scrcmd.disassemble` can walk a script. Generated by
scripts/gen_scrcmd_args.py; the decomp's macros are the authority for the shapes, and
scrcmd_names.COMMANDS for the names.

A macro with a variable tail (the trainerbattle family, whose operands depend on their first byte)
is absent here rather than guessed: `disassemble` stops at an opcode it has no shape for and says
so, which is the honest answer for a byte stream that may not be a script at all.
"""

# opcode -> (operand widths in bytes)
ARGS = {
'''

WIDTHS = {".byte": 1, ".2byte": 2, ".4byte": 4}


def main():
    text = (DECOMP / "asm" / "macros" / "event.inc").read_text()
    table = {}
    for block in re.findall(r"^\s*\.macro\s+(\w+)([^\n]*)\n(.*?)^\s*\.endm", text,
                            re.M | re.S):
        name, _params, body = block
        emits = re.findall(r"^\s*(\.byte|\.2byte|\.4byte)\s+(.+)$", body, re.M)
        if not emits or emits[0][0] != ".byte":
            continue                      # a helper macro, not a command
        try:
            opcode = int(emits[0][1].strip().split()[0], 0)
        except ValueError:
            continue                      # the opcode itself is symbolic: not a command macro
        if any(w not in WIDTHS for w, _ in emits[1:]):
            continue
        widths = tuple(WIDTHS[w] for w, _ in emits[1:])
        if opcode in table and table[opcode][1] != widths:
            continue                      # two macros, two shapes: leave it out rather than guess
        table.setdefault(opcode, (name, widths))
    lines = [HEADER]
    for opcode in sorted(table):
        name, widths = table[opcode]
        lines.append(f"    0x{opcode:02X}: {widths!r},".replace(",)", ",)") + f"    # {name}")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(table)} commands with a fixed shape)")


if __name__ == "__main__":
    main()
