#!/usr/bin/env python3
"""Regenerate frlgsim/symbol_names.py: the var and flag ids, by name, from the decomp's headers.

    ./.venv/bin/python scripts/gen_symbol_names.py [~/pokefirered]

A field script's operands are bare numbers, and the two that carry meaning everywhere are the var
id and the flag id. `include/constants/vars.h` and `include/constants/flags.h` name every one, but
as arithmetic on other constants (`VAR_TEMP_0` is `(TEMP_VARS_START + 0x0)`), so the values are
evaluated here rather than transcribed.

Several names can share a value - the decomp keeps `FLAG_TEMP_1` alongside a `FLAG_0x001` style
alias for the ones it has not identified. The FIRST definition in file order wins, which is the
identified name, and the rest are kept in ALIASES so nothing is lost.

WHY THE VALUE ALONE IS ENOUGH to tell a var from a literal: every ScrCmd body passes its arguments
through `VarGet`, which returns the number unchanged unless it is >= VARS_START and otherwise reads
the variable [decomp:src/event_data.c:235, GetVarPointer:214]. So an operand of 0x4000 or more IS a
variable reference, in any command, and one below it is the literal it looks like. No per-command
table and no guessing.
"""
import pathlib
import re
import sys

DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "~/pokefirered").expanduser()
OUT = pathlib.Path(__file__).resolve().parent.parent / "frlgsim" / "symbol_names.py"

# flags.h builds the trainer flags on the TRAINER_* ids and the system flags on MAX_TRAINERS_COUNT,
# so the headers it takes those from have to be read with it.
SOURCES = {
    "VARS": ("include/constants/vars.h",),
    "FLAGS": ("include/constants/opponents.h", "include/constants/trainers.h",
              "include/constants/flags.h"),
}

# `[ \t]`, never `\s`: `\s` matches a newline, so a valueless guard (`#define GUARD_..._H`) would
# swallow the next line as its value and that define would vanish from the table.
DEFINE = re.compile(r"^#define[ \t]+(\w+)[ \t]+([^\n]+?)[ \t]*$", re.M)


def defines(paths):
    """-> {name: expression} for every #define in `paths`, in file order."""
    out = {}
    for path in paths:
        for name, expression in DEFINE.findall((DECOMP / path).read_text()):
            if "(" in name:                       # a function-like macro, not a constant
                continue
            out.setdefault(name, expression.split("//")[0].strip())
    return out


def evaluate(name, expressions, resolving=()):
    """-> the integer value of a #define, resolving the constants it is written in terms of."""
    if name in resolving:
        raise SystemExit(f"{name} is defined in terms of itself")
    expression = expressions[name]
    def substitute(match):
        word = match.group(0)
        if re.fullmatch(r"0[xX][0-9a-fA-F]+|\d+", word):
            return word
        if word not in expressions:
            raise LookupError(word)
        return str(evaluate(word, expressions, resolving + (name,)))
    try:
        return int(eval(re.sub(r"\w+", substitute, expression), {"__builtins__": {}}, {}))
    except LookupError:
        raise
    except Exception as error:
        raise SystemExit(f"cannot evaluate {name} = {expression!r}: {error}")


def table(paths, prefix):
    """-> ({value: name}, {value: [other names]}) for every `prefix`-named constant."""
    expressions = defines(paths)
    values, aliases = {}, {}
    for name in expressions:
        if not name.startswith(prefix):
            continue
        try:
            value = evaluate(name, expressions)
        except LookupError:
            continue                              # names a constant from a header we do not read
        if value in values:
            aliases.setdefault(value, []).append(name)
        else:
            values[value] = name
    return values, aliases


def render(title, values, aliases):
    lines = [f"{title} = {{"]
    for value in sorted(values):
        lines.append(f"    0x{value:04X}: {values[value]!r},")
    lines.append("}")
    lines.append("")
    lines.append(f"{title}_ALIASES = {{")
    for value in sorted(aliases):
        lines.append(f"    0x{value:04X}: {aliases[value]!r},")
    lines.append("}")
    lines.append("")
    return lines


def main():
    variables, var_aliases = table(SOURCES["VARS"], "VAR_")
    flags, flag_aliases = table(SOURCES["FLAGS"], "FLAG_")
    bounds = defines(SOURCES["VARS"])

    header = f'''"""Var and flag ids by name [decomp:include/constants/vars.h, include/constants/flags.h].

Generated by scripts/gen_symbol_names.py. VARS and FLAGS map an id to the decomp's name; the
_ALIASES tables hold the other names the decomp gives the same id.

An operand is a VARIABLE REFERENCE exactly when it is >= VARS_START: every ScrCmd body passes its
arguments through `VarGet`, which returns the number unchanged below that and reads the variable at
or above it [decomp:src/event_data.c:235]. `is_var` is that test, and it needs no per-command
table - which is why a disassembler can name the operands of a command it knows nothing else about.

0x4000..0x40FF are the saved variables and 0x8000..0x8014 the 21 `gSpecialVars`; between them is a
gap `GetVarPointer` reads past the end of the saved array, so nothing legitimate uses it.
"""

VARS_START = 0x{int(evaluate("VARS_START", bounds)):04X}
VARS_END = 0x{int(evaluate("VARS_END", bounds)):04X}
SPECIAL_VARS_START = 0x{int(evaluate("SPECIAL_VARS_START", bounds)):04X}
SPECIAL_VARS_END = 0x{int(evaluate("SPECIAL_VARS_END", bounds)):04X}


def is_var(value):
    """-> whether an operand is a variable reference rather than the literal it looks like."""
    return value >= VARS_START


def var_name(value):
    """-> the decomp's name for a var id, or a readable placeholder for an id it does not name."""
    return VARS.get(value, f"VAR_{{value:04X}}" if is_var(value) else f"0x{{value:04X}}")


def flag_name(value):
    return FLAGS.get(value, f"FLAG_{{value:04X}}")

'''
    lines = [header] + render("VARS", variables, var_aliases) + render("FLAGS", flags, flag_aliases)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(variables)} vars, {len(flags)} flags, "
          f"{sum(map(len, var_aliases.values())) + sum(map(len, flag_aliases.values()))} aliases)")


if __name__ == "__main__":
    main()
